.TH "src/third_parties/fast_max-clique_finder/src/findCliqueHeu.cpp" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/third_parties/fast_max-clique_finder/src/findCliqueHeu.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'findClique\&.h'\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFMC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBFMC::maxCliqueHeu\fP (CGraphIO &gio)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBFMC::maxDegree\fP"
.br
.ti -1c
.RI "int \fBFMC::maxClq\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
