.TH "src/third_parties/fast_max-clique_finder/src/findClique.cpp" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/third_parties/fast_max-clique_finder/src/findClique.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'findClique\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFMC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFMC::maxCliqueHelper\fP (CGraphIO &gio, vector< int > *U, int sizeOfClique, int &maxClq, vector< int > &max_clique_data_inter)"
.br
.ti -1c
.RI "int \fBFMC::maxClique\fP (CGraphIO &gio, int l_bound, vector< int > &max_clique_data)"
.br
.ti -1c
.RI "void \fBFMC::print_max_clique\fP (vector< int > &max_clique_data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBFMC::pruned1\fP"
.br
.ti -1c
.RI "int \fBFMC::pruned2\fP"
.br
.ti -1c
.RI "int \fBFMC::pruned3\fP"
.br
.ti -1c
.RI "int \fBFMC::pruned5\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
