.TH "FMC" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FMC \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGraphIO\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< int > \fBIntVector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmaxCliqueHelper\fP (\fBCGraphIO\fP &gio, vector< int > *U, int sizeOfClique, int &\fBmaxClq\fP, vector< int > &max_clique_data_inter)"
.br
.ti -1c
.RI "int \fBmaxClique\fP (\fBCGraphIO\fP &gio, int l_bound, vector< int > &max_clique_data)"
.br
.ti -1c
.RI "void \fBprint_max_clique\fP (vector< int > &max_clique_data)"
.br
.ti -1c
.RI "bool \fBfexists\fP (const char *filename)"
.br
.ti -1c
.RI "double \fBwtime\fP ()"
.br
.ti -1c
.RI "void \fBusage\fP (char *argv0)"
.br
.ti -1c
.RI "int \fBgetDegree\fP (vector< int > *ptrVtx, int idx)"
.br
.ti -1c
.RI "int \fBmaxCliqueHeu\fP (\fBCGraphIO\fP &gio)"
.br
.ti -1c
.RI "void \fBmaxCliqueHelperHeu\fP (\fBCGraphIO\fP &gio, vector< int > *U, int sizeOfClique, int &\fBmaxClq\fP, vector< int > &max_clique_data_inter)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBpruned1\fP"
.br
.ti -1c
.RI "int \fBpruned2\fP"
.br
.ti -1c
.RI "int \fBpruned3\fP"
.br
.ti -1c
.RI "int \fBpruned5\fP"
.br
.ti -1c
.RI "int \fBmaxDegree\fP"
.br
.ti -1c
.RI "int \fBmaxClq\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<int> \fBFMC::IntVector\fP"

.PP
Definition at line 36 of file graphIO\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool FMC::fexists (const char * filename)"

.PP
Definition at line 23 of file utils\&.cpp\&.
.SS "int FMC::getDegree (vector< int > * ptrVtx, int idx)"

.PP
Definition at line 48 of file utils\&.cpp\&.
.SS "int FMC::maxClique (\fBCGraphIO\fP & gio, int l_bound, vector< int > & max_clique_data)"

.PP
Definition at line 83 of file findClique\&.cpp\&.
.SS "void FMC::maxCliqueHelper (\fBCGraphIO\fP & gio, vector< int > * U, int sizeOfClique, int & maxClq, vector< int > & max_clique_data_inter)"

.PP
Definition at line 29 of file findClique\&.cpp\&.
.SS "void FMC::maxCliqueHelperHeu (\fBCGraphIO\fP & gio, vector< int > * U, int sizeOfClique, int & maxClq, vector< int > & max_clique_data_inter)"

.SS "int FMC::maxCliqueHeu (\fBCGraphIO\fP & gio)"

.PP
Definition at line 30 of file findCliqueHeu\&.cpp\&.
.SS "void FMC::print_max_clique (vector< int > & max_clique_data)"

.PP
Definition at line 156 of file findClique\&.cpp\&.
.SS "void FMC::usage (char * argv0)"

.PP
Definition at line 36 of file utils\&.cpp\&.
.SS "double FMC::wtime ()"

.PP
Definition at line 29 of file utils\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int FMC::maxClq"

.PP
Definition at line 27 of file findCliqueHeu\&.cpp\&.
.SS "int FMC::maxDegree"

.PP
Definition at line 27 of file findCliqueHeu\&.cpp\&.
.SS "int FMC::pruned1"

.PP
Definition at line 23 of file findClique\&.cpp\&.
.SS "int FMC::pruned2"

.PP
Definition at line 24 of file findClique\&.cpp\&.
.SS "int FMC::pruned3"

.PP
Definition at line 25 of file findClique\&.cpp\&.
.SS "int FMC::pruned5"

.PP
Definition at line 26 of file findClique\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
