.TH "generate_cached_setup" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generate_cached_setup \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpython_path\fP = os\&.path\&.join(workspace, 'lib/python2\&.7/dist\-packages')"
.br
.ti -1c
.RI "\fBcode\fP = generate_environment_script('/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/devel/env\&.sh')"
.br
.ti -1c
.RI "string \fBoutput_filename\fP = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/catkin_generated/setup_cached\&.sh'"
.br
.ti -1c
.RI "\fBmode\fP = os\&.stat(\fBoutput_filename\fP)\&.st_mode"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "generate_cached_setup\&.code = generate_environment_script('/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/devel/env\&.sh')"

.PP
Definition at line 22 of file generate_cached_setup\&.py\&.
.SS "generate_cached_setup\&.mode = os\&.stat(\fBoutput_filename\fP)\&.st_mode"

.PP
Definition at line 29 of file generate_cached_setup\&.py\&.
.SS "string generate_cached_setup\&.output_filename = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/catkin_generated/setup_cached\&.sh'"

.PP
Definition at line 24 of file generate_cached_setup\&.py\&.
.SS "generate_cached_setup\&.python_path = os\&.path\&.join(workspace, 'lib/python2\&.7/dist\-packages')"

.PP
Definition at line 16 of file generate_cached_setup\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
