.TH "global_map_solver::GlobalMapSolver" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
global_map_solver::GlobalMapSolver \- Class computing the global map from multiple robots local maps\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global_map_solver\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobalMapSolver\fP (const \fBrobot_local_map::RobotLocalMap\fP &robot1_local_map, const \fBrobot_local_map::RobotLocalMap\fP &robot2_local_map, const \fBrobot_local_map::RobotMeasurements\fP &interrobot_measurements)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "int \fBsolveGlobalMap\fP ()"
.br
.RI "\fIFunction that solves the global maps according to the current constraints\&. \fP"
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBCONSISTENCY_MATRIX_FILE_NAME\fP = std::string('consistency_matrix\&.clq\&.mtx')"
.br
.RI "\fIFile name in which the consistency matrix will be saved\&. \fP"
.ti -1c
.RI "static const std::string \fBCONSISTENCY_LOOP_CLOSURES_FILE_NAME\fP = std::string('consistent_loop_closures\&.txt')"
.br
.RI "\fIFile name in which the consistent loop closures will be saved\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBpairwise_consistency::PairwiseConsistency\fP \fBpairwise_consistency_\fP"
.br
.RI "\fIPairwise consistency solver\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class computing the global map from multiple robots local maps\&. 
.PP
Definition at line 14 of file global_map_solver\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "global_map_solver::GlobalMapSolver::GlobalMapSolver (const \fBrobot_local_map::RobotLocalMap\fP & robot1_local_map, const \fBrobot_local_map::RobotLocalMap\fP & robot2_local_map, const \fBrobot_local_map::RobotMeasurements\fP & interrobot_measurements)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrobot1_local_map\fP Local map of robot 1\&. 
.br
\fIrobot2_local_map\fP Local map of robot 2\&. 
.br
\fIinterrobot_measurements\fP Inter-robot measurements\&. 
.RE
.PP

.PP
Definition at line 11 of file global_map_solver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int global_map_solver::GlobalMapSolver::solveGlobalMap ()"

.PP
Function that solves the global maps according to the current constraints\&. 
.PP
\fBReturns:\fP
.RS 4
the size of the maximum clique\&. 
.RE
.PP

.PP
Definition at line 19 of file global_map_solver\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string global_map_solver::GlobalMapSolver::CONSISTENCY_LOOP_CLOSURES_FILE_NAME = std::string('consistent_loop_closures\&.txt')\fC [static]\fP"

.PP
File name in which the consistent loop closures will be saved\&. 
.PP
Definition at line 24 of file global_map_solver\&.h\&.
.SS "const std::string global_map_solver::GlobalMapSolver::CONSISTENCY_MATRIX_FILE_NAME = std::string('consistency_matrix\&.clq\&.mtx')\fC [static]\fP"

.PP
File name in which the consistency matrix will be saved\&. 
.PP
Definition at line 19 of file global_map_solver\&.h\&.
.SS "\fBpairwise_consistency::PairwiseConsistency\fP global_map_solver::GlobalMapSolver::pairwise_consistency_\fC [private]\fP"

.PP
Pairwise consistency solver\&. 
.PP
Definition at line 45 of file global_map_solver\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
