.TH "include/global_map_solver/global_map_solver.h" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/global_map_solver/global_map_solver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'robot_local_map/robot_local_map\&.h'\fP
.br
\fC#include 'pairwise_consistency/pairwise_consistency\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglobal_map_solver::GlobalMapSolver\fP"
.br
.RI "\fIClass computing the global map from multiple robots local maps\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglobal_map_solver\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
