.TH "include/graph_utils/graph_types.h" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/graph_utils/graph_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'geometry_msgs/PoseWithCovariance\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBgraph_utils::Transform\fP"
.br
.RI "\fIStructure defining a transformation between two poses\&. \fP"
.ti -1c
.RI "struct \fBgraph_utils::Transforms\fP"
.br
.RI "\fIStructure defining a std::map of transformations\&. \fP"
.ti -1c
.RI "struct \fBgraph_utils::TrajectoryPose\fP"
.br
.RI "\fIStructure defining a pose in a robot trajectory\&. \fP"
.ti -1c
.RI "struct \fBgraph_utils::Trajectory\fP"
.br
.RI "\fIStructure defining a robot trajectory\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgraph_utils\fP"
.br
.RI "\fIThis namespace encapsulates utility functions to manipulate graphs\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< std::pair< size_t, size_t > > \fBgraph_utils::LoopClosures\fP"
.br
.RI "\fItype to store poses IDs of loop closures\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
