.TH "graph_utils::Transform" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph_utils::Transform \- Structure defining a transformation between two poses\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graph_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBi\fP"
.br
.ti -1c
.RI "size_t \fBj\fP"
.br
.ti -1c
.RI "geometry_msgs::PoseWithCovariance \fBpose\fP"
.br
.ti -1c
.RI "bool \fBis_loop_closure\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure defining a transformation between two poses\&. 
.PP
Definition at line 19 of file graph_types\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t graph_utils::Transform::i"

.PP
Definition at line 20 of file graph_types\&.h\&.
.SS "bool graph_utils::Transform::is_loop_closure"

.PP
Definition at line 22 of file graph_types\&.h\&.
.SS "size_t graph_utils::Transform::j"

.PP
Definition at line 20 of file graph_types\&.h\&.
.SS "geometry_msgs::PoseWithCovariance graph_utils::Transform::pose"

.PP
Definition at line 21 of file graph_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
