.TH "pairwise_consistency::PairwiseConsistency" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pairwise_consistency::PairwiseConsistency \- Class for the computation of the pairwise consistency of loop closure edges\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pairwise_consistency\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPairwiseConsistency\fP (const \fBgraph_utils::Transforms\fP &transforms_robot1, const \fBgraph_utils::Transforms\fP &transforms_robot2, const \fBgraph_utils::Transforms\fP &transforms_interrobot, const \fBgraph_utils::LoopClosures\fP &loop_closures, const \fBgraph_utils::Trajectory\fP &trajectory_robot1, const \fBgraph_utils::Trajectory\fP &trajectory_robot2, uint8_t nb_degree_freedom)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "Eigen::MatrixXi \fBcomputeConsistentMeasurementsMatrix\fP ()"
.br
.RI "\fIComputation of the consistency matrix\&. \fP"
.ti -1c
.RI "const \fBgraph_utils::LoopClosures\fP & \fBgetLoopClosures\fP () const "
.br
.RI "\fIAccessor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class for the computation of the pairwise consistency of loop closure edges\&. 
.PP
Definition at line 19 of file pairwise_consistency\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pairwise_consistency::PairwiseConsistency::PairwiseConsistency (const \fBgraph_utils::Transforms\fP & transforms_robot1, const \fBgraph_utils::Transforms\fP & transforms_robot2, const \fBgraph_utils::Transforms\fP & transforms_interrobot, const \fBgraph_utils::LoopClosures\fP & loop_closures, const \fBgraph_utils::Trajectory\fP & trajectory_robot1, const \fBgraph_utils::Trajectory\fP & trajectory_robot2, uint8_t nb_degree_freedom)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fItransforms_robot1\fP Measurements of robot 1 
.br
\fItransforms_robot2\fP Measurements of robot 2 
.br
\fItransforms_interrobot\fP Inter-robot measurements 
.br
\fIloop_closures\fP Nodes ID in loop closures 
.br
\fItrajectory_robot1\fP Precomputed trajectory of robot 1 
.br
\fItrajectory_robot2\fP Precomputed trajectory of robot 2 
.br
\fInb_degree_freedom\fP Number of degree of freedom of the robots measurements\&. 
.RE
.PP

.PP
Definition at line 32 of file pairwise_consistency\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "Eigen::MatrixXi pairwise_consistency::PairwiseConsistency::computeConsistentMeasurementsMatrix ()"

.PP
Computation of the consistency matrix\&. 
.PP
\fBReturns:\fP
.RS 4
the consistency matrix 
.RE
.PP

.PP
Definition at line 7 of file pairwise_consistency\&.cpp\&.
.SS "const \fBgraph_utils::LoopClosures\fP & pairwise_consistency::PairwiseConsistency::getLoopClosures () const"

.PP
Accessor\&. 
.PP
\fBReturns:\fP
.RS 4
list of loop closures 
.RE
.PP

.PP
Definition at line 125 of file pairwise_consistency\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
