.TH "include/pairwise_consistency/pairwise_consistency.h" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pairwise_consistency/pairwise_consistency.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'graph_utils/graph_utils_functions\&.h'\fP
.br
\fC#include 'geometry_msgs/PoseWithCovariance\&.h'\fP
.br
\fC#include <eigen3/Eigen/Geometry>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpairwise_consistency::PairwiseConsistency\fP"
.br
.RI "\fIClass for the computation of the pairwise consistency of loop closure edges\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpairwise_consistency\fP"
.br
.RI "\fIThis namespace encapsulates the tools for the pairwise consistency computation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
