.TH "cmake-build-debug/catkin_generated/pkg.develspace.context.pc.py" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/catkin_generated/pkg.develspace.context.pc.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpkg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBpkg\&.CATKIN_PACKAGE_PREFIX\fP = ''"
.br
.ti -1c
.RI "string \fBpkg\&.PROJECT_PKG_CONFIG_INCLUDE_DIRS\fP = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/include'"
.br
.ti -1c
.RI "string \fBpkg\&.PROJECT_CATKIN_DEPENDS\fP = 'geometry_msgs;mrpt_bridge'"
.br
.ti -1c
.RI "string \fBpkg\&.PKG_CONFIG_LIBRARIES_WITH_PREFIX\fP = '\-lpairwise_consistency;\-lgraph_utils'"
.br
.ti -1c
.RI "string \fBpkg\&.PROJECT_NAME\fP = 'robust_multirobot_map_merging'"
.br
.ti -1c
.RI "string \fBpkg\&.PROJECT_SPACE_DIR\fP = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/devel'"
.br
.ti -1c
.RI "string \fBpkg\&.PROJECT_VERSION\fP = '0\&.0\&.0'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
