.TH "pkg" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkg \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBCATKIN_PACKAGE_PREFIX\fP = ''"
.br
.ti -1c
.RI "string \fBPROJECT_PKG_CONFIG_INCLUDE_DIRS\fP = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/include'"
.br
.ti -1c
.RI "string \fBPROJECT_CATKIN_DEPENDS\fP = 'geometry_msgs;mrpt_bridge'"
.br
.ti -1c
.RI "string \fBPKG_CONFIG_LIBRARIES_WITH_PREFIX\fP = '\-lpairwise_consistency;\-lgraph_utils'"
.br
.ti -1c
.RI "string \fBPROJECT_NAME\fP = 'robust_multirobot_map_merging'"
.br
.ti -1c
.RI "string \fBPROJECT_SPACE_DIR\fP = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/devel'"
.br
.ti -1c
.RI "string \fBPROJECT_VERSION\fP = '0\&.0\&.0'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string pkg\&.CATKIN_PACKAGE_PREFIX = ''"

.PP
Definition at line 2 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SS "string pkg\&.PKG_CONFIG_LIBRARIES_WITH_PREFIX = '\-lpairwise_consistency;\-lgraph_utils'"

.PP
Definition at line 5 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SS "string pkg\&.PROJECT_CATKIN_DEPENDS = 'geometry_msgs;mrpt_bridge'"

.PP
Definition at line 4 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SS "string pkg\&.PROJECT_NAME = 'robust_multirobot_map_merging'"

.PP
Definition at line 6 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SS "string pkg\&.PROJECT_PKG_CONFIG_INCLUDE_DIRS = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/include'"

.PP
Definition at line 3 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SS "string pkg\&.PROJECT_SPACE_DIR = '/home/lajoiepy/Documents/master/mit/baseline_ws/src/robust_multirobot_map_merging/cmake\-build\-debug/devel'"

.PP
Definition at line 7 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SS "string pkg\&.PROJECT_VERSION = '0\&.0\&.0'"

.PP
Definition at line 8 of file pkg\&.develspace\&.context\&.pc\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
