.TH "robot_local_map" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robot_local_map \- This namespace encapsulates classes and functions related to the local maps of the individual robots\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRobotLocalMap\fP"
.br
.ti -1c
.RI "class \fBRobotMeasurements\fP"
.br
.RI "\fIClass that contains the measurements of a single robot\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This namespace encapsulates classes and functions related to the local maps of the individual robots\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
