.TH "robot_local_map::RobotLocalMap" 3 "Tue Sep 11 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robot_local_map::RobotLocalMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robot_local_map\&.h>\fP
.PP
Inherits \fBrobot_local_map::RobotMeasurements\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRobotLocalMap\fP (const std::string &file_name)"
.br
.ti -1c
.RI "const \fBgraph_utils::Trajectory\fP & \fBgetTrajectory\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class that contains the local map of a single robot\&. 
.PP
Definition at line 12 of file robot_local_map\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "robot_local_map::RobotLocalMap::RobotLocalMap (const std::string & file_name)"
Constructor 
.PP
Definition at line 8 of file robot_local_map\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBgraph_utils::Trajectory\fP & robot_local_map::RobotLocalMap::getTrajectory () const"
Accessors 
.PP
Definition at line 12 of file robot_local_map\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
