.TH "include/robot_local_map/robot_measurements.h" 3 "Wed Sep 12 2018" "Version 0.1" "robust_multirobot_map_merging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/robot_local_map/robot_measurements.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'graph_utils/graph_types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrobot_local_map::RobotMeasurements\fP"
.br
.RI "\fIClass that contains the measurements of a single robot\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrobot_local_map\fP"
.br
.RI "\fIThis namespace encapsulates classes and functions related to the local maps of the individual robots\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for robust_multirobot_map_merging from the source code\&.
